//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TupleGeneratorWrapper {

public class CartesianRangeInterval : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CartesianRangeInterval(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CartesianRangeInterval obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CartesianRangeInterval obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CartesianRangeInterval() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TupleGeneratorPINVOKE.delete_CartesianRangeInterval(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public cTuple ql {
    set {
      TupleGeneratorPINVOKE.CartesianRangeInterval_ql_set(swigCPtr, cTuple.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TupleGeneratorPINVOKE.CartesianRangeInterval_ql_get(swigCPtr);
      cTuple ret = (cPtr == global::System.IntPtr.Zero) ? null : new cTuple(cPtr, false);
      return ret;
    } 
  }

  public cTuple qh {
    set {
      TupleGeneratorPINVOKE.CartesianRangeInterval_qh_set(swigCPtr, cTuple.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TupleGeneratorPINVOKE.CartesianRangeInterval_qh_get(swigCPtr);
      cTuple ret = (cPtr == global::System.IntPtr.Zero) ? null : new cTuple(cPtr, false);
      return ret;
    } 
  }

  public vector_cTuple_ptr tuples {
    set {
      TupleGeneratorPINVOKE.CartesianRangeInterval_tuples_set(swigCPtr, vector_cTuple_ptr.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TupleGeneratorPINVOKE.CartesianRangeInterval_tuples_get(swigCPtr);
      vector_cTuple_ptr ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_cTuple_ptr(cPtr, false);
      return ret;
    } 
  }

  public CartesianRangeInterval() : this(TupleGeneratorPINVOKE.new_CartesianRangeInterval(), true) {
  }

}

}
