//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TupleGeneratorWrapper {

public class cDataType : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal cDataType(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(cDataType obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(cDataType obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~cDataType() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TupleGeneratorPINVOKE.delete_cDataType(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual char GetCode() {
    char ret = TupleGeneratorPINVOKE.cDataType_GetCode(swigCPtr);
    return ret;
  }

  public virtual int CompareArray(string array1, string array2, uint length) {
    int ret = TupleGeneratorPINVOKE.cDataType_CompareArray(swigCPtr, array1, array2, length);
    return ret;
  }

  public virtual bool IsIntersected(string ql1, string qh1, string ql2, string qh2, uint length) {
    bool ret = TupleGeneratorPINVOKE.cDataType_IsIntersected(swigCPtr, ql1, qh1, ql2, qh2, length);
    return ret;
  }

  public virtual bool IsInRectangle(string ql, string qh, string t, uint length) {
    bool ret = TupleGeneratorPINVOKE.cDataType_IsInRectangle(swigCPtr, ql, qh, t, length);
    return ret;
  }

  public virtual uint HashValue(string array, uint length, uint hashTableSize) {
    uint ret = TupleGeneratorPINVOKE.cDataType_HashValue(swigCPtr, array, length, hashTableSize);
    return ret;
  }

  public virtual uint GetSize_instance(string mem, cDTDescriptor dTd) {
    uint ret = TupleGeneratorPINVOKE.cDataType_GetSize_instance__SWIG_0(swigCPtr, mem, cDTDescriptor.getCPtr(dTd));
    return ret;
  }

  public virtual uint GetSize_instance(string mem) {
    uint ret = TupleGeneratorPINVOKE.cDataType_GetSize_instance__SWIG_1(swigCPtr, mem);
    return ret;
  }

  public virtual uint GetSize(cDTDescriptor dTd) {
    uint ret = TupleGeneratorPINVOKE.cDataType_GetSize__SWIG_0(swigCPtr, cDTDescriptor.getCPtr(dTd));
    return ret;
  }

  public virtual uint GetSize() {
    uint ret = TupleGeneratorPINVOKE.cDataType_GetSize__SWIG_1(swigCPtr);
    return ret;
  }

  public virtual uint GetSize(uint itemSize) {
    uint ret = TupleGeneratorPINVOKE.cDataType_GetSize__SWIG_2(swigCPtr, itemSize);
    return ret;
  }

  public virtual uint GetMaxSize(cDTDescriptor dTd) {
    uint ret = TupleGeneratorPINVOKE.cDataType_GetMaxSize(swigCPtr, cDTDescriptor.getCPtr(dTd));
    return ret;
  }

  public static readonly char SER_SIZE = TupleGeneratorPINVOKE.cDataType_SER_SIZE_get();
  public static readonly uint CHAR_BIT_LENGTH = TupleGeneratorPINVOKE.cDataType_CHAR_BIT_LENGTH_get();
  public static readonly char CODE = TupleGeneratorPINVOKE.cDataType_CODE_get();
  public static readonly uint LENGTH_VARLEN = TupleGeneratorPINVOKE.cDataType_LENGTH_VARLEN_get();
  public static readonly uint LENGTH_FIXLEN = TupleGeneratorPINVOKE.cDataType_LENGTH_FIXLEN_get();
  public static readonly uint NOT_DEFINED = TupleGeneratorPINVOKE.cDataType_NOT_DEFINED_get();
  public static readonly char CODE_NTUPLE = TupleGeneratorPINVOKE.cDataType_CODE_NTUPLE_get();
  public static readonly char CODE_LNTUPLE = TupleGeneratorPINVOKE.cDataType_CODE_LNTUPLE_get();
}

}
