//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TupleGeneratorWrapper {

public class CollectionGeneratorBase : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CollectionGeneratorBase(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CollectionGeneratorBase obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CollectionGeneratorBase obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CollectionGeneratorBase() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TupleGeneratorPINVOKE.delete_CollectionGeneratorBase(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual cSpaceDescriptor GetSpaceDescriptor() {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.CollectionGeneratorBase_GetSpaceDescriptor(swigCPtr);
    cSpaceDescriptor ret = (cPtr == global::System.IntPtr.Zero) ? null : new cSpaceDescriptor(cPtr, false);
    return ret;
  }

  public virtual uint GetTupleCount() {
    uint ret = TupleGeneratorPINVOKE.CollectionGeneratorBase_GetTupleCount(swigCPtr);
    return ret;
  }

  public virtual uint GetQueriesCount() {
    uint ret = TupleGeneratorPINVOKE.CollectionGeneratorBase_GetQueriesCount(swigCPtr);
    return ret;
  }

  public virtual uint GetDimension() {
    uint ret = TupleGeneratorPINVOKE.CollectionGeneratorBase_GetDimension(swigCPtr);
    return ret;
  }

  public virtual void Load() {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_Load(swigCPtr);
  }

  public virtual void GeneratePointQueries(uint pQueriesCount, double pPercentage) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GeneratePointQueries__SWIG_0(swigCPtr, pQueriesCount, pPercentage);
  }

  public virtual void GeneratePointQueries(uint pQueriesCount) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GeneratePointQueries__SWIG_1(swigCPtr, pQueriesCount);
  }

  public virtual void GeneratePartialMatchQueries(uint pQueriesCount, double pPercentage) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GeneratePartialMatchQueries__SWIG_0(swigCPtr, pQueriesCount, pPercentage);
  }

  public virtual void GeneratePartialMatchQueries(uint pQueriesCount) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GeneratePartialMatchQueries__SWIG_1(swigCPtr, pQueriesCount);
  }

  public virtual void GenerateNarrowRangeQueries(uint pQueriesCount, uint pDispersion, double pProbability, string pMask, double pPercentage) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GenerateNarrowRangeQueries__SWIG_0(swigCPtr, pQueriesCount, pDispersion, pProbability, pMask, pPercentage);
  }

  public virtual void GenerateNarrowRangeQueries(uint pQueriesCount, uint pDispersion, double pProbability, string pMask) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GenerateNarrowRangeQueries__SWIG_1(swigCPtr, pQueriesCount, pDispersion, pProbability, pMask);
  }

  public virtual void GenerateNarrowRangeQueries(uint pQueriesCount, uint pDispersion, double pProbability) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GenerateNarrowRangeQueries__SWIG_2(swigCPtr, pQueriesCount, pDispersion, pProbability);
  }

  public virtual void GenerateRangeQueries(uint pQueriesCount, uint pQuerysetSizeStart, uint pQuerysetSizeEnd) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GenerateRangeQueries(swigCPtr, pQueriesCount, pQuerysetSizeStart, pQuerysetSizeEnd);
  }

  public virtual void GenerateCartesianRangeQueries(uint pQueriesCount, uint pQuerysetSizeStart, uint pQuerysetSizeEnd, uint pIntervals) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GenerateCartesianRangeQueries(swigCPtr, pQueriesCount, pQuerysetSizeStart, pQuerysetSizeEnd, pIntervals);
  }

  public virtual void ExportCollection(CollectionToExport pCollection, string pCollectionName) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_ExportCollection__SWIG_0(swigCPtr, (int)pCollection, pCollectionName);
  }

  public virtual void ExportCollection(CollectionToExport pCollection) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_ExportCollection__SWIG_1(swigCPtr, (int)pCollection);
  }

  public virtual void GenerateSQLSelects(string pCollectionName) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GenerateSQLSelects__SWIG_0(swigCPtr, pCollectionName);
  }

  public virtual void GenerateSQLSelects() {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GenerateSQLSelects__SWIG_1(swigCPtr);
  }

  public virtual void GenerateSQLInserts(string pCollectionName) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GenerateSQLInserts__SWIG_0(swigCPtr, pCollectionName);
  }

  public virtual void GenerateSQLInserts() {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_GenerateSQLInserts__SWIG_1(swigCPtr);
  }

  public virtual cTuple GetTuple(uint pOrder) {
    cTuple ret = new cTuple(TupleGeneratorPINVOKE.CollectionGeneratorBase_GetTuple(swigCPtr, pOrder), true);
    return ret;
  }

  public virtual cTuple GetQuery(uint pOrder) {
    cTuple ret = new cTuple(TupleGeneratorPINVOKE.CollectionGeneratorBase_GetQuery(swigCPtr, pOrder), true);
    return ret;
  }

  public virtual void PrintHistogram(string pFileName, uint pIntervalCount) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_PrintHistogram__SWIG_0(swigCPtr, pFileName, pIntervalCount);
  }

  public virtual void PrintHistogram(string pFileName) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_PrintHistogram__SWIG_1(swigCPtr, pFileName);
  }

  public virtual string PrintHistogram(uint pIntervalCount) {
    string ret = TupleGeneratorPINVOKE.CollectionGeneratorBase_PrintHistogram__SWIG_2(swigCPtr, pIntervalCount);
    return ret;
  }

  public virtual string PrintHistogram() {
    string ret = TupleGeneratorPINVOKE.CollectionGeneratorBase_PrintHistogram__SWIG_3(swigCPtr);
    return ret;
  }

  public virtual void SortTuples(TypeOfSort pTypeOfSort) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_SortTuples__SWIG_0(swigCPtr, (int)pTypeOfSort);
  }

  public virtual void SortTuples() {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_SortTuples__SWIG_1(swigCPtr);
  }

  public virtual void UnsortTuples() {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_UnsortTuples(swigCPtr);
  }

  public virtual RangeQuery GetRangeQuery(uint pIndex) {
    RangeQuery ret = new RangeQuery(TupleGeneratorPINVOKE.CollectionGeneratorBase_GetRangeQuery(swigCPtr, pIndex), false);
    return ret;
  }

  public virtual uint GetRangeQueriesCount() {
    uint ret = TupleGeneratorPINVOKE.CollectionGeneratorBase_GetRangeQueriesCount(swigCPtr);
    return ret;
  }

  public virtual CartesianRangeQuery GetCartesianRangeQuery(uint pIndex) {
    CartesianRangeQuery ret = new CartesianRangeQuery(TupleGeneratorPINVOKE.CollectionGeneratorBase_GetCartesianRangeQuery(swigCPtr, pIndex), false);
    return ret;
  }

  public virtual uint GetCartesianRangeQueriesCount() {
    uint ret = TupleGeneratorPINVOKE.CollectionGeneratorBase_GetCartesianRangeQueriesCount(swigCPtr);
    return ret;
  }

  public virtual bool IsZOrdered() {
    bool ret = TupleGeneratorPINVOKE.CollectionGeneratorBase_IsZOrdered(swigCPtr);
    return ret;
  }

  public virtual bool IsZOrderSortCacheValid() {
    bool ret = TupleGeneratorPINVOKE.CollectionGeneratorBase_IsZOrderSortCacheValid(swigCPtr);
    return ret;
  }

  public virtual void Cleanup() {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_Cleanup(swigCPtr);
  }

  public virtual void CloseQueryStream() {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_CloseQueryStream(swigCPtr);
  }

  public void SetProgress(int pValue) {
    TupleGeneratorPINVOKE.CollectionGeneratorBase_SetProgress(swigCPtr, pValue);
  }

  public int GetProgress() {
    int ret = TupleGeneratorPINVOKE.CollectionGeneratorBase_GetProgress(swigCPtr);
    return ret;
  }

}

}
