//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TupleGeneratorWrapper {

public class CollectionGenerator_cDouble : CollectionGeneratorBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CollectionGenerator_cDouble(global::System.IntPtr cPtr, bool cMemoryOwn) : base(TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CollectionGenerator_cDouble obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CollectionGenerator_cDouble obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TupleGeneratorPINVOKE.delete_CollectionGenerator_cDouble(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public class HistogramCache : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal HistogramCache(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HistogramCache obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(HistogramCache obj) {
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
        global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.Dispose();
        return ptr;
      } else {
        return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  
    ~HistogramCache() {
      Dispose(false);
    }
  
    public void Dispose() {
      Dispose(true);
      global::System.GC.SuppressFinalize(this);
    }
  
    protected virtual void Dispose(bool disposing) {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            TupleGeneratorPINVOKE.delete_CollectionGenerator_cDouble_HistogramCache(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
      }
    }
  
    public bool isValid {
      set {
        TupleGeneratorPINVOKE.CollectionGenerator_cDouble_HistogramCache_isValid_set(swigCPtr, value);
      } 
      get {
        bool ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_HistogramCache_isValid_get(swigCPtr);
        return ret;
      } 
    }
  
    public uint intervalCount {
      set {
        TupleGeneratorPINVOKE.CollectionGenerator_cDouble_HistogramCache_intervalCount_set(swigCPtr, value);
      } 
      get {
        uint ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_HistogramCache_intervalCount_get(swigCPtr);
        return ret;
      } 
    }
  
    public string data {
      set {
        TupleGeneratorPINVOKE.CollectionGenerator_cDouble_HistogramCache_data_set(swigCPtr, value);
        if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        string ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_HistogramCache_data_get(swigCPtr);
        if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public HistogramCache() : this(TupleGeneratorPINVOKE.new_CollectionGenerator_cDouble_HistogramCache(), true) {
    }
  
  }

  public class SortCache : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal SortCache(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SortCache obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SortCache obj) {
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
        global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.Dispose();
        return ptr;
      } else {
        return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  
    ~SortCache() {
      Dispose(false);
    }
  
    public void Dispose() {
      Dispose(true);
      global::System.GC.SuppressFinalize(this);
    }
  
    protected virtual void Dispose(bool disposing) {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            TupleGeneratorPINVOKE.delete_CollectionGenerator_cDouble_SortCache(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
      }
    }
  
    public bool isValid {
      set {
        TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SortCache_isValid_set(swigCPtr, value);
      } 
      get {
        bool ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SortCache_isValid_get(swigCPtr);
        return ret;
      } 
    }
  
    public vector_uint indexes {
      set {
        TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SortCache_indexes_set(swigCPtr, vector_uint.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SortCache_indexes_get(swigCPtr);
        vector_uint ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_uint(cPtr, false);
        return ret;
      } 
    }
  
    public SortCache() : this(TupleGeneratorPINVOKE.new_CollectionGenerator_cDouble_SortCache(), true) {
    }
  
  }

  public void SetPercentage(double pPercentage) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SetPercentage(swigCPtr, pPercentage);
  }

  public void SetBuffer(double pBuffer) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SetBuffer(swigCPtr, pBuffer);
  }

  public void SetProbability(double pProbability) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SetProbability(swigCPtr, pProbability);
  }

  public void SetDigits(int pDigits) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SetDigits(swigCPtr, pDigits);
  }

  public void SetMean(uint pMean) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SetMean(swigCPtr, pMean);
  }

  public void SetStdDeviation(uint pStdDeviation) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SetStdDeviation(swigCPtr, pStdDeviation);
  }

  public void SetBufferSize(uint pBufferSize) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SetBufferSize(swigCPtr, pBufferSize);
  }

  public void SetMaxLineLength(uint pMaxLineLength) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SetMaxLineLength(swigCPtr, pMaxLineLength);
  }

  public override cSpaceDescriptor GetSpaceDescriptor() {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GetSpaceDescriptor(swigCPtr);
    cSpaceDescriptor ret = (cPtr == global::System.IntPtr.Zero) ? null : new cSpaceDescriptor(cPtr, false);
    return ret;
  }

  public override uint GetTupleCount() {
    uint ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GetTupleCount(swigCPtr);
    return ret;
  }

  public override uint GetQueriesCount() {
    uint ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GetQueriesCount(swigCPtr);
    return ret;
  }

  public override uint GetDimension() {
    uint ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GetDimension(swigCPtr);
    return ret;
  }

  public CollectionGenerator_cDouble() : this(TupleGeneratorPINVOKE.new_CollectionGenerator_cDouble__SWIG_0(), true) {
  }

  public CollectionGenerator_cDouble(string pFileName) : this(TupleGeneratorPINVOKE.new_CollectionGenerator_cDouble__SWIG_1(pFileName), true) {
  }

  public CollectionGenerator_cDouble(uint pDimension, uint pTupleCount, Distribution pDistribution) : this(TupleGeneratorPINVOKE.new_CollectionGenerator_cDouble__SWIG_2(pDimension, pTupleCount, (int)pDistribution), true) {
  }

  public CollectionGenerator_cDouble(uint pDimension, uint pTupleCount, Distribution pDistribution, uint pMinValue, uint pMaxValue) : this(TupleGeneratorPINVOKE.new_CollectionGenerator_cDouble__SWIG_3(pDimension, pTupleCount, (int)pDistribution, pMinValue, pMaxValue), true) {
  }

  public void SetDataSource(string pFileName) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SetDataSource__SWIG_0(swigCPtr, pFileName);
  }

  public void SetDataSource(uint pDimension, uint pTupleCount) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SetDataSource__SWIG_1(swigCPtr, pDimension, pTupleCount);
  }

  public void SetDataSource(uint pDimension, uint pTupleCount, Distribution pDistribution) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SetDataSource__SWIG_2(swigCPtr, pDimension, pTupleCount, (int)pDistribution);
  }

  public override void Load() {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_Load(swigCPtr);
  }

  public override void PrintHistogram(string pFileName, uint pIntervalCount) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_PrintHistogram__SWIG_0(swigCPtr, pFileName, pIntervalCount);
  }

  public override void PrintHistogram(string pFileName) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_PrintHistogram__SWIG_1(swigCPtr, pFileName);
  }

  public override string PrintHistogram(uint pIntervalCount) {
    string ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_PrintHistogram__SWIG_2(swigCPtr, pIntervalCount);
    return ret;
  }

  public override string PrintHistogram() {
    string ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_PrintHistogram__SWIG_3(swigCPtr);
    return ret;
  }

  public override void SortTuples(TypeOfSort pTypeOfSort) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SortTuples__SWIG_0(swigCPtr, (int)pTypeOfSort);
  }

  public override void SortTuples() {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_SortTuples__SWIG_1(swigCPtr);
  }

  public override void UnsortTuples() {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_UnsortTuples(swigCPtr);
  }

  public override void GeneratePointQueries(uint pQueriesCount, double pPercentage) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GeneratePointQueries__SWIG_0(swigCPtr, pQueriesCount, pPercentage);
  }

  public override void GeneratePointQueries(uint pQueriesCount) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GeneratePointQueries__SWIG_1(swigCPtr, pQueriesCount);
  }

  public override void GeneratePartialMatchQueries(uint pQueriesCount, double pPercentage) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GeneratePartialMatchQueries__SWIG_0(swigCPtr, pQueriesCount, pPercentage);
  }

  public override void GeneratePartialMatchQueries(uint pQueriesCount) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GeneratePartialMatchQueries__SWIG_1(swigCPtr, pQueriesCount);
  }

  public override void GenerateRangeQueries(uint pQueriesCount, uint pQuerysetSizeStart, uint pQuerysetSizeEnd) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GenerateRangeQueries(swigCPtr, pQueriesCount, pQuerysetSizeStart, pQuerysetSizeEnd);
  }

  public override void GenerateNarrowRangeQueries(uint pQueriesCount, uint pDispersion, double pProbability, string pMask, double pPercentage) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GenerateNarrowRangeQueries__SWIG_0(swigCPtr, pQueriesCount, pDispersion, pProbability, pMask, pPercentage);
  }

  public override void GenerateNarrowRangeQueries(uint pQueriesCount, uint pDispersion, double pProbability, string pMask) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GenerateNarrowRangeQueries__SWIG_1(swigCPtr, pQueriesCount, pDispersion, pProbability, pMask);
  }

  public override void GenerateNarrowRangeQueries(uint pQueriesCount, uint pDispersion, double pProbability) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GenerateNarrowRangeQueries__SWIG_2(swigCPtr, pQueriesCount, pDispersion, pProbability);
  }

  public override void GenerateCartesianRangeQueries(uint pQueriesCount, uint pQuerysetSizeStart, uint pQuerysetSizeEnd, uint pIntervals) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GenerateCartesianRangeQueries(swigCPtr, pQueriesCount, pQuerysetSizeStart, pQuerysetSizeEnd, pIntervals);
  }

  public override void ExportCollection(CollectionToExport pCollection, string pCollectionName) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_ExportCollection__SWIG_0(swigCPtr, (int)pCollection, pCollectionName);
  }

  public override void ExportCollection(CollectionToExport pCollection) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_ExportCollection__SWIG_1(swigCPtr, (int)pCollection);
  }

  public void ExportTuples(string pCollectionName) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_ExportTuples(swigCPtr, pCollectionName);
  }

  public void ExportQueries(string pCollectionName) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_ExportQueries(swigCPtr, pCollectionName);
  }

  public override void GenerateSQLSelects(string pCollectionName) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GenerateSQLSelects__SWIG_0(swigCPtr, pCollectionName);
  }

  public override void GenerateSQLSelects() {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GenerateSQLSelects__SWIG_1(swigCPtr);
  }

  public override void GenerateSQLInserts(string pCollectionName) {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GenerateSQLInserts__SWIG_0(swigCPtr, pCollectionName);
  }

  public override void GenerateSQLInserts() {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GenerateSQLInserts__SWIG_1(swigCPtr);
  }

  public override cTuple GetTuple(uint pOrder) {
    cTuple ret = new cTuple(TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GetTuple(swigCPtr, pOrder), true);
    return ret;
  }

  public override cTuple GetQuery(uint pOrder) {
    cTuple ret = new cTuple(TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GetQuery(swigCPtr, pOrder), true);
    return ret;
  }

  public override RangeQuery GetRangeQuery(uint pIndex) {
    RangeQuery ret = new RangeQuery(TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GetRangeQuery(swigCPtr, pIndex), false);
    return ret;
  }

  public override uint GetRangeQueriesCount() {
    uint ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GetRangeQueriesCount(swigCPtr);
    return ret;
  }

  public override CartesianRangeQuery GetCartesianRangeQuery(uint pIndex) {
    CartesianRangeQuery ret = new CartesianRangeQuery(TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GetCartesianRangeQuery(swigCPtr, pIndex), false);
    return ret;
  }

  public override uint GetCartesianRangeQueriesCount() {
    uint ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_GetCartesianRangeQueriesCount(swigCPtr);
    return ret;
  }

  public override bool IsZOrdered() {
    bool ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_IsZOrdered(swigCPtr);
    return ret;
  }

  public override bool IsZOrderSortCacheValid() {
    bool ret = TupleGeneratorPINVOKE.CollectionGenerator_cDouble_IsZOrderSortCacheValid(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_wstring ConvertToWString(string pString) {
    SWIGTYPE_p_wstring ret = new SWIGTYPE_p_wstring(TupleGeneratorPINVOKE.CollectionGenerator_cDouble_ConvertToWString(swigCPtr, pString), true);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void Cleanup() {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_Cleanup(swigCPtr);
  }

  public override void CloseQueryStream() {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_CloseQueryStream(swigCPtr);
  }

  public void CleanupZAddressMapping() {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_CleanupZAddressMapping(swigCPtr);
  }

  public void CleanupAlphabeticalMapping() {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_CleanupAlphabeticalMapping(swigCPtr);
  }

  public void CleanupImportMapping() {
    TupleGeneratorPINVOKE.CollectionGenerator_cDouble_CleanupImportMapping(swigCPtr);
  }

}

}
