//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TupleGeneratorWrapper {

public class cSpaceDescriptor : cDTDescriptor {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal cSpaceDescriptor(global::System.IntPtr cPtr, bool cMemoryOwn) : base(TupleGeneratorPINVOKE.cSpaceDescriptor_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(cSpaceDescriptor obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(cSpaceDescriptor obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TupleGeneratorPINVOKE.delete_cSpaceDescriptor(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public cSpaceDescriptor(uint dimension, cDataType type, cDataType dimensionType) : this(TupleGeneratorPINVOKE.new_cSpaceDescriptor__SWIG_0(dimension, cDataType.getCPtr(type), cDataType.getCPtr(dimensionType)), true) {
  }

  public cSpaceDescriptor(uint dimension, cDataType type) : this(TupleGeneratorPINVOKE.new_cSpaceDescriptor__SWIG_1(dimension, cDataType.getCPtr(type)), true) {
  }

  public cSpaceDescriptor(uint dimension, cDataType type, cDataType dimensionType, bool computeOrderValues) : this(TupleGeneratorPINVOKE.new_cSpaceDescriptor__SWIG_2(dimension, cDataType.getCPtr(type), cDataType.getCPtr(dimensionType), computeOrderValues), true) {
  }

  public void Create(uint dimension, cDataType type, cDataType dimensionType) {
    TupleGeneratorPINVOKE.cSpaceDescriptor_Create__SWIG_0(swigCPtr, dimension, cDataType.getCPtr(type), cDataType.getCPtr(dimensionType));
  }

  public void Create(cSpaceDescriptor treeSpaceDescriptor) {
    TupleGeneratorPINVOKE.cSpaceDescriptor_Create__SWIG_1(swigCPtr, cSpaceDescriptor.getCPtr(treeSpaceDescriptor));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetDimensionType(uint dim, cDataType type) {
    TupleGeneratorPINVOKE.cSpaceDescriptor_SetDimensionType(swigCPtr, dim, cDataType.getCPtr(type));
  }

  public cDataType GetDimensionType(uint dim) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cSpaceDescriptor_GetDimensionType(swigCPtr, dim);
    cDataType ret = (cPtr == global::System.IntPtr.Zero) ? null : new cDataType(cPtr, false);
    return ret;
  }

  public char GetDimensionTypeCode(uint dim) {
    char ret = TupleGeneratorPINVOKE.cSpaceDescriptor_GetDimensionTypeCode(swigCPtr, dim);
    return ret;
  }

  public uint GetBitIndex(uint order) {
    uint ret = TupleGeneratorPINVOKE.cSpaceDescriptor_GetBitIndex(swigCPtr, order);
    return ret;
  }

  public uint GetDimensionOrder(uint order) {
    uint ret = TupleGeneratorPINVOKE.cSpaceDescriptor_GetDimensionOrder(swigCPtr, order);
    return ret;
  }

  public uint GetDimensionSize(uint order) {
    uint ret = TupleGeneratorPINVOKE.cSpaceDescriptor_GetDimensionSize(swigCPtr, order);
    return ret;
  }

  public uint GetSize() {
    uint ret = TupleGeneratorPINVOKE.cSpaceDescriptor_GetSize(swigCPtr);
    return ret;
  }

  public uint GetTypeSize() {
    uint ret = TupleGeneratorPINVOKE.cSpaceDescriptor_GetTypeSize(swigCPtr);
    return ret;
  }

  public uint GetLSize(uint tupleLength) {
    uint ret = TupleGeneratorPINVOKE.cSpaceDescriptor_GetLSize(swigCPtr, tupleLength);
    return ret;
  }

  public uint GetSerialSize() {
    uint ret = TupleGeneratorPINVOKE.cSpaceDescriptor_GetSerialSize(swigCPtr);
    return ret;
  }

  public bool IsSpaceHomogenous() {
    bool ret = TupleGeneratorPINVOKE.cSpaceDescriptor_IsSpaceHomogenous(swigCPtr);
    return ret;
  }

  public void Setup() {
    TupleGeneratorPINVOKE.cSpaceDescriptor_Setup(swigCPtr);
  }

  public cDataType CreateDataType(char code) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cSpaceDescriptor_CreateDataType(swigCPtr, code);
    cDataType ret = (cPtr == global::System.IntPtr.Zero) ? null : new cDataType(cPtr, false);
    return ret;
  }

  public cSpaceDescriptor GetDimSpaceDescriptor(uint order) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cSpaceDescriptor_GetDimSpaceDescriptor(swigCPtr, order);
    cSpaceDescriptor ret = (cPtr == global::System.IntPtr.Zero) ? null : new cSpaceDescriptor(cPtr, false);
    return ret;
  }

  public void SetDimSpaceDescriptor(uint order, cSpaceDescriptor sd) {
    TupleGeneratorPINVOKE.cSpaceDescriptor_SetDimSpaceDescriptor(swigCPtr, order, cSpaceDescriptor.getCPtr(sd));
  }

  public bool IsAnyDimDescriptor() {
    bool ret = TupleGeneratorPINVOKE.cSpaceDescriptor_IsAnyDimDescriptor(swigCPtr);
    return ret;
  }

  public bool Read(SWIGTYPE_p_cStream stream) {
    bool ret = TupleGeneratorPINVOKE.cSpaceDescriptor_Read(swigCPtr, SWIGTYPE_p_cStream.getCPtr(stream));
    return ret;
  }

  public bool Write(SWIGTYPE_p_cStream stream) {
    bool ret = TupleGeneratorPINVOKE.cSpaceDescriptor_Write(swigCPtr, SWIGTYPE_p_cStream.getCPtr(stream));
    return ret;
  }

  public int CompareNormalizedZValues(string tuple1, string tuple2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cSpaceDescriptor_CompareNormalizedZValues(swigCPtr, tuple1, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public int CompareNormalizedHValues(string tuple1, string tuple2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cSpaceDescriptor_CompareNormalizedHValues(swigCPtr, tuple1, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public void ComputeNormalizedValues(string tuple1, string tuple2, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cSpaceDescriptor_ComputeNormalizedValues(swigCPtr, tuple1, tuple2, cSpaceDescriptor.getCPtr(pSd));
  }

  public void ComputeNormalizedUnitSize() {
    TupleGeneratorPINVOKE.cSpaceDescriptor_ComputeNormalizedUnitSize(swigCPtr);
  }

}

}
