//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TupleGeneratorWrapper {

public class cTuple : cDataType {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal cTuple(global::System.IntPtr cPtr, bool cMemoryOwn) : base(TupleGeneratorPINVOKE.cTuple_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(cTuple obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(cTuple obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TupleGeneratorPINVOKE.delete_cTuple(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public override char GetCode() {
    char ret = TupleGeneratorPINVOKE.cTuple_GetCode(swigCPtr);
    return ret;
  }

  public static uint countCompare {
    set {
      TupleGeneratorPINVOKE.cTuple_countCompare_set(value);
    } 
    get {
      uint ret = TupleGeneratorPINVOKE.cTuple_countCompare_get();
      return ret;
    } 
  }

  public static uint basicCountCompare {
    set {
      TupleGeneratorPINVOKE.cTuple_basicCountCompare_set(value);
    } 
    get {
      uint ret = TupleGeneratorPINVOKE.cTuple_basicCountCompare_get();
      return ret;
    } 
  }

  public static uint countCompareOrder {
    set {
      TupleGeneratorPINVOKE.cTuple_countCompareOrder_set(value);
    } 
    get {
      uint ret = TupleGeneratorPINVOKE.cTuple_countCompareOrder_get();
      return ret;
    } 
  }

  public static double basicTotalReadNodes {
    set {
      TupleGeneratorPINVOKE.cTuple_basicTotalReadNodes_set(value);
    } 
    get {
      double ret = TupleGeneratorPINVOKE.cTuple_basicTotalReadNodes_get();
      return ret;
    } 
  }

  public static SWIGTYPE_p_unsigned_int countCompareLevel {
    set {
      TupleGeneratorPINVOKE.cTuple_countCompareLevel_set(SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cTuple_countCompareLevel_get();
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public static uint levelTree {
    set {
      TupleGeneratorPINVOKE.cTuple_levelTree_set(value);
    } 
    get {
      uint ret = TupleGeneratorPINVOKE.cTuple_levelTree_get();
      return ret;
    } 
  }

  public static SWIGTYPE_p_unsigned_int readNodesInLevel {
    set {
      TupleGeneratorPINVOKE.cTuple_readNodesInLevel_set(SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cTuple_readNodesInLevel_get();
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public static SWIGTYPE_p_unsigned_int itemsCountForLevel {
    set {
      TupleGeneratorPINVOKE.cTuple_itemsCountForLevel_set(SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cTuple_itemsCountForLevel_get();
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public static bool typeRQordered {
    set {
      TupleGeneratorPINVOKE.cTuple_typeRQordered_set(value);
    } 
    get {
      bool ret = TupleGeneratorPINVOKE.cTuple_typeRQordered_get();
      return ret;
    } 
  }

  public static uint typeRQ {
    set {
      TupleGeneratorPINVOKE.cTuple_typeRQ_set(value);
    } 
    get {
      uint ret = TupleGeneratorPINVOKE.cTuple_typeRQ_get();
      return ret;
    } 
  }

  public static uint callCountCompare {
    set {
      TupleGeneratorPINVOKE.cTuple_callCountCompare_set(value);
    } 
    get {
      uint ret = TupleGeneratorPINVOKE.cTuple_callCountCompare_get();
      return ret;
    } 
  }

  public static uint addItemOrder {
    set {
      TupleGeneratorPINVOKE.cTuple_addItemOrder_set(value);
    } 
    get {
      uint ret = TupleGeneratorPINVOKE.cTuple_addItemOrder_get();
      return ret;
    } 
  }

  public int flagRQ {
    set {
      TupleGeneratorPINVOKE.cTuple_flagRQ_set(swigCPtr, value);
    } 
    get {
      int ret = TupleGeneratorPINVOKE.cTuple_flagRQ_get(swigCPtr);
      return ret;
    } 
  }

  public static float indexSizeMB {
    set {
      TupleGeneratorPINVOKE.cTuple_indexSizeMB_set(value);
    } 
    get {
      float ret = TupleGeneratorPINVOKE.cTuple_indexSizeMB_get();
      return ret;
    } 
  }

  public static uint tupleLeafCountItems {
    set {
      TupleGeneratorPINVOKE.cTuple_tupleLeafCountItems_set(value);
    } 
    get {
      uint ret = TupleGeneratorPINVOKE.cTuple_tupleLeafCountItems_get();
      return ret;
    } 
  }

  public static uint leafItemsCount {
    set {
      TupleGeneratorPINVOKE.cTuple_leafItemsCount_set(value);
    } 
    get {
      uint ret = TupleGeneratorPINVOKE.cTuple_leafItemsCount_get();
      return ret;
    } 
  }

  public static int GetObjectSize(cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_GetObjectSize(cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public void Free(SWIGTYPE_p_cMemoryBlock memBlock) {
    TupleGeneratorPINVOKE.cTuple_Free__SWIG_0(swigCPtr, SWIGTYPE_p_cMemoryBlock.getCPtr(memBlock));
  }

  public void Free() {
    TupleGeneratorPINVOKE.cTuple_Free__SWIG_1(swigCPtr);
  }

  public bool Resize(cSpaceDescriptor pSd, SWIGTYPE_p_cMemoryBlock memBlock) {
    bool ret = TupleGeneratorPINVOKE.cTuple_Resize__SWIG_0(swigCPtr, cSpaceDescriptor.getCPtr(pSd), SWIGTYPE_p_cMemoryBlock.getCPtr(memBlock));
    return ret;
  }

  public bool Resize(cSpaceDescriptor pSd) {
    bool ret = TupleGeneratorPINVOKE.cTuple_Resize__SWIG_1(swigCPtr, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public bool Resize(cDTDescriptor pSd, uint length) {
    bool ret = TupleGeneratorPINVOKE.cTuple_Resize__SWIG_2(swigCPtr, cDTDescriptor.getCPtr(pSd), length);
    return ret;
  }

  public bool Resize(cDTDescriptor pSd) {
    bool ret = TupleGeneratorPINVOKE.cTuple_Resize__SWIG_3(swigCPtr, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public string Init(string mem) {
    string ret = TupleGeneratorPINVOKE.cTuple_Init(swigCPtr, mem);
    return ret;
  }

  public void SetValue(cTuple tuple, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_0(swigCPtr, cTuple.getCPtr(tuple), cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetFlagRQ(uint value) {
    TupleGeneratorPINVOKE.cTuple_SetFlagRQ(swigCPtr, value);
  }

  public void SetValue(uint order, float value, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_1(swigCPtr, order, value, cDTDescriptor.getCPtr(pSd));
  }

  public void SetValue(uint order, double value, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_2(swigCPtr, order, value, cDTDescriptor.getCPtr(pSd));
  }

  public void SetValue(uint order, int value, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_3(swigCPtr, order, value, cDTDescriptor.getCPtr(pSd));
  }

  public void SetValue(uint order, uint value, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_4(swigCPtr, order, value, cDTDescriptor.getCPtr(pSd));
  }

  public void SetValue(uint order, char value, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_5(swigCPtr, order, value, cDTDescriptor.getCPtr(pSd));
  }

  public void SetValue(uint order, byte value, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_6(swigCPtr, order, value, cDTDescriptor.getCPtr(pSd));
  }

  public void SetValue(uint order, ushort value, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_8(swigCPtr, order, value, cDTDescriptor.getCPtr(pSd));
  }

  public void SetValue(uint order, short value, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_9(swigCPtr, order, value, cDTDescriptor.getCPtr(pSd));
  }

  public void SetValue(uint order, string cTuple_value, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_10(swigCPtr, order, cTuple_value, cDTDescriptor.getCPtr(pSd));
  }

  public void SetMaxValues(cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetMaxValues(swigCPtr, cSpaceDescriptor.getCPtr(pSd));
  }

  public void SetMaxValue(uint order, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetMaxValue(swigCPtr, order, cSpaceDescriptor.getCPtr(pSd));
  }

  public void Clear(cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_Clear__SWIG_0(swigCPtr, cSpaceDescriptor.getCPtr(pSd));
  }

  public void Clear(uint order, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_Clear__SWIG_1(swigCPtr, order, cSpaceDescriptor.getCPtr(pSd));
  }

  public void ClearOther(uint order, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_ClearOther(swigCPtr, order, cSpaceDescriptor.getCPtr(pSd));
  }

  public float GetFloat(uint order, cDTDescriptor pSd) {
    float ret = TupleGeneratorPINVOKE.cTuple_GetFloat__SWIG_0(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public double GetDouble(uint order, cDTDescriptor pSd) {
    double ret = TupleGeneratorPINVOKE.cTuple_GetDouble__SWIG_0(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public int GetInt(uint order, cDTDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_GetInt__SWIG_0(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public uint GetUInt(uint order, cDTDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetUInt__SWIG_0(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public char GetByte(uint order, cDTDescriptor pSd) {
    char ret = TupleGeneratorPINVOKE.cTuple_GetByte__SWIG_0(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public byte GetUChar(uint order, cDTDescriptor pSd) {
    byte ret = TupleGeneratorPINVOKE.cTuple_GetUChar__SWIG_0(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public short GetShort(uint order, cDTDescriptor pSd) {
    short ret = TupleGeneratorPINVOKE.cTuple_GetShort__SWIG_0(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public ushort GetUShort(uint order, cDTDescriptor pSd) {
    ushort ret = TupleGeneratorPINVOKE.cTuple_GetUShort__SWIG_0(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public void GetString(uint order, SWIGTYPE_p_cString string_, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_GetString(swigCPtr, order, SWIGTYPE_p_cString.getCPtr(string_), cDTDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public char GetWChar(uint order, cDTDescriptor pSd) {
    char ret = TupleGeneratorPINVOKE.cTuple_GetWChar(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public string GetTuple(uint order, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_GetTuple__SWIG_0(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public string GetPValue(uint order, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_GetPValue__SWIG_0(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static string GetTuple(string data, uint order, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_GetTuple__SWIG_1(data, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public SWIGTYPE_p_float GetPFloat(uint order, cDTDescriptor pSd) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cTuple_GetPFloat(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_int GetPInt(uint order, cDTDescriptor pSd) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cTuple_GetPInt(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_unsigned_int GetPUInt(uint order, cDTDescriptor pSd) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cTuple_GetPUInt(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
    return ret;
  }

  public string GetPByte(uint order, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_GetPByte(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public SWIGTYPE_p_unsigned_char GetPUChar(uint order, cDTDescriptor pSd) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cTuple_GetPUChar(swigCPtr, order, cDTDescriptor.getCPtr(pSd));
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public bool IsZero(uint order, cSpaceDescriptor pSd) {
    bool ret = TupleGeneratorPINVOKE.cTuple_IsZero__SWIG_0(swigCPtr, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public bool IsZero(cSpaceDescriptor pSd) {
    bool ret = TupleGeneratorPINVOKE.cTuple_IsZero__SWIG_1(swigCPtr, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public override uint GetSize(cDTDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetSize__SWIG_0(swigCPtr, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public override uint GetSize_instance(string data, cDTDescriptor pDtd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetSize_instance(swigCPtr, data, cDTDescriptor.getCPtr(pDtd));
    return ret;
  }

  public override uint GetSize(uint tupleSize) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetSize__SWIG_1(swigCPtr, tupleSize);
    return ret;
  }

  public override uint GetMaxSize(cDTDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetMaxSize__SWIG_0(swigCPtr, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public uint GetSerialSize(cDTDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetSerialSize(swigCPtr, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public string GetData() {
    string ret = TupleGeneratorPINVOKE.cTuple_GetData(swigCPtr);
    return ret;
  }

  public void SetData(string data) {
    TupleGeneratorPINVOKE.cTuple_SetData(swigCPtr, data);
  }

  public uint GetRealDimension(cSpaceDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetRealDimension__SWIG_0(swigCPtr, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public uint GetRealDimension(uint hi, cSpaceDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetRealDimension__SWIG_1(swigCPtr, hi, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public double EuclidianIntDistance(cTuple tuple, cSpaceDescriptor pSd) {
    double ret = TupleGeneratorPINVOKE.cTuple_EuclidianIntDistance(swigCPtr, cTuple.getCPtr(tuple), cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float UnitIntervalLength(cTuple tuple, uint order, cSpaceDescriptor pSd) {
    float ret = TupleGeneratorPINVOKE.cTuple_UnitIntervalLength__SWIG_0(swigCPtr, cTuple.getCPtr(tuple), order, cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int CompareZOrder(string tuple1, string tuple2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_CompareZOrder(tuple1, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static int CompareHOrder(string tuple1, string tuple2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_CompareHOrder(tuple1, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static int CompareTaxiOrder(string tuple1, string tuple2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_CompareTaxiOrder(tuple1, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public override int CompareArray(string array1, string array2, uint length) {
    int ret = TupleGeneratorPINVOKE.cTuple_CompareArray(swigCPtr, array1, array2, length);
    return ret;
  }

  public override bool IsIntersected(string ql1, string qh1, string ql2, string qh2, uint length) {
    bool ret = TupleGeneratorPINVOKE.cTuple_IsIntersected(swigCPtr, ql1, qh1, ql2, qh2, length);
    return ret;
  }

  public override bool IsInRectangle(string ql, string qh, string t, uint length) {
    bool ret = TupleGeneratorPINVOKE.cTuple_IsInRectangle(swigCPtr, ql, qh, t, length);
    return ret;
  }

  public override uint HashValue(string array, uint length, uint hashTableSize) {
    uint ret = TupleGeneratorPINVOKE.cTuple_HashValue__SWIG_0(swigCPtr, array, length, hashTableSize);
    return ret;
  }

  public bool Read(SWIGTYPE_p_cStream stream, cSpaceDescriptor pSd) {
    bool ret = TupleGeneratorPINVOKE.cTuple_Read(swigCPtr, SWIGTYPE_p_cStream.getCPtr(stream), cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public bool Write(SWIGTYPE_p_cStream stream, cSpaceDescriptor pSd) {
    bool ret = TupleGeneratorPINVOKE.cTuple_Write(swigCPtr, SWIGTYPE_p_cStream.getCPtr(stream), cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public int Equal(cTuple tuple, uint order, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Equal__SWIG_0(swigCPtr, cTuple.getCPtr(tuple), order, cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Equal(cTuple tuple, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Equal__SWIG_1(swigCPtr, cTuple.getCPtr(tuple), cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Equal(string tuple2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Equal__SWIG_2(swigCPtr, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public bool Equal(uint start, uint k, cTuple tuple, cSpaceDescriptor pSd) {
    bool ret = TupleGeneratorPINVOKE.cTuple_Equal__SWIG_3(swigCPtr, start, k, cTuple.getCPtr(tuple), cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Compare(cTuple tuple, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Compare__SWIG_0(swigCPtr, cTuple.getCPtr(tuple), cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int CompareLexicographically(string tuple2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_CompareLexicographically__SWIG_0(swigCPtr, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public int CompareLexicographically(cTuple tuple, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_CompareLexicographically__SWIG_1(swigCPtr, cTuple.getCPtr(tuple), cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int Compare_uint(SWIGTYPE_p_unsigned_int t1, SWIGTYPE_p_unsigned_int t2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Compare_uint(SWIGTYPE_p_unsigned_int.getCPtr(t1), SWIGTYPE_p_unsigned_int.getCPtr(t2), cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public void Copy(cTuple tuple) {
    TupleGeneratorPINVOKE.cTuple_Copy__SWIG_0(swigCPtr, cTuple.getCPtr(tuple));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint CopyTo(string data, cSpaceDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_CopyTo__SWIG_0(swigCPtr, data, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public uint CopyTo(string data, cDTDescriptor pDtD) {
    uint ret = TupleGeneratorPINVOKE.cTuple_CopyTo__SWIG_1(swigCPtr, data, cDTDescriptor.getCPtr(pDtD));
    return ret;
  }

  public uint Copy(string srcData, cSpaceDescriptor pDtD) {
    uint ret = TupleGeneratorPINVOKE.cTuple_Copy__SWIG_1(swigCPtr, srcData, cSpaceDescriptor.getCPtr(pDtD));
    return ret;
  }

  public uint Copy(string srcData, cDTDescriptor pDtD) {
    uint ret = TupleGeneratorPINVOKE.cTuple_Copy__SWIG_2(swigCPtr, srcData, cDTDescriptor.getCPtr(pDtD));
    return ret;
  }

  public string Print(string string_, cSpaceDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_Print__SWIG_0(swigCPtr, string_, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public string Print(string string_, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_Print__SWIG_1(swigCPtr, string_, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public string Print(uint order, string string_, cSpaceDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_Print__SWIG_2(swigCPtr, order, string_, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public string PrintPM(string delim, cTuple refTuple, cSpaceDescriptor pSd, bool isQL) {
    string ret = TupleGeneratorPINVOKE.cTuple_PrintPM(swigCPtr, delim, cTuple.getCPtr(refTuple), cSpaceDescriptor.getCPtr(pSd), isQL);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string PrintPM_QL(string delim, cTuple qh, cSpaceDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_PrintPM_QL(swigCPtr, delim, cTuple.getCPtr(qh), cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string PrintPM_QH(string delim, cTuple ql, cSpaceDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_PrintPM_QH(swigCPtr, delim, cTuple.getCPtr(ql), cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint HashValue(uint hashTableSize, cDTDescriptor dtd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_HashValue__SWIG_1(swigCPtr, hashTableSize, cDTDescriptor.getCPtr(dtd));
    return ret;
  }

  public uint OrderedHashValue(cDTDescriptor dtd, uint hashType, uint hashArg) {
    uint ret = TupleGeneratorPINVOKE.cTuple_OrderedHashValue__SWIG_0(swigCPtr, cDTDescriptor.getCPtr(dtd), hashType, hashArg);
    return ret;
  }

  public uint OrderedHashValue(cDTDescriptor dtd, uint hashType) {
    uint ret = TupleGeneratorPINVOKE.cTuple_OrderedHashValue__SWIG_1(swigCPtr, cDTDescriptor.getCPtr(dtd), hashType);
    return ret;
  }

  public uint OrderedHashValue(cDTDescriptor dtd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_OrderedHashValue__SWIG_2(swigCPtr, cDTDescriptor.getCPtr(dtd));
    return ret;
  }

  public void ComputeHAddress(SWIGTYPE_p_cBitString hvalue, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_ComputeHAddress(swigCPtr, SWIGTYPE_p_cBitString.getCPtr(hvalue), cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public int Compare(string tuple2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Compare__SWIG_1(swigCPtr, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public int Compare(string tuple2, cDTDescriptor dd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Compare__SWIG_2(swigCPtr, tuple2, cDTDescriptor.getCPtr(dd));
    return ret;
  }

  public static void Clear(string data, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_Clear__SWIG_2(data, cSpaceDescriptor.getCPtr(pSd));
  }

  public static void SetTuple(string data, cTuple tuple, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetTuple__SWIG_0(data, cTuple.getCPtr(tuple), cSpaceDescriptor.getCPtr(pSd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void SetTuple(string dst_data, string src_data, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetTuple__SWIG_1(dst_data, src_data, cSpaceDescriptor.getCPtr(pSd));
  }

  public static cTuple GetValue(string value, cDTDescriptor pSd) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cTuple_GetValue(value, cDTDescriptor.getCPtr(pSd));
    cTuple ret = (cPtr == global::System.IntPtr.Zero) ? null : new cTuple(cPtr, false);
    return ret;
  }

  public static cTuple GetValueC(string value, cDTDescriptor pSd) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.cTuple_GetValueC(value, cDTDescriptor.getCPtr(pSd));
    cTuple ret = (cPtr == global::System.IntPtr.Zero) ? null : new cTuple(cPtr, false);
    return ret;
  }

  public static bool ResizeSet(cTuple t1, cTuple t2, cDTDescriptor pSd, SWIGTYPE_p_cMemoryBlock memBlock) {
    bool ret = TupleGeneratorPINVOKE.cTuple_ResizeSet(cTuple.getCPtr(t1), cTuple.getCPtr(t2), cDTDescriptor.getCPtr(pSd), SWIGTYPE_p_cMemoryBlock.getCPtr(memBlock));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void Copy(string cUnfTuple_dst, string cUnfTuple_src, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_Copy__SWIG_3(cUnfTuple_dst, cUnfTuple_src, cDTDescriptor.getCPtr(pSd));
  }

  public static bool IsEqual(string tuple1, string tuple2, cSpaceDescriptor pSd) {
    bool ret = TupleGeneratorPINVOKE.cTuple_IsEqual__SWIG_0(tuple1, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static bool IsEqual(string tuple1, string tuple2, cDTDescriptor pDtd) {
    bool ret = TupleGeneratorPINVOKE.cTuple_IsEqual__SWIG_1(tuple1, tuple2, cDTDescriptor.getCPtr(pDtd));
    return ret;
  }

  public static int Equal(string tuple1, string tuple2, uint tupleLength, cDTDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Equal__SWIG_4(tuple1, tuple2, tupleLength, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static int Equal(string tuple, string tuple2, uint order, cSpaceDescriptor pSd, uint bitMask) {
    int ret = TupleGeneratorPINVOKE.cTuple_Equal__SWIG_5(tuple, tuple2, order, cSpaceDescriptor.getCPtr(pSd), bitMask);
    return ret;
  }

  public static int Equal(string tuple1, string tuple2, cDTDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Equal__SWIG_6(tuple1, tuple2, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static int Equal(string tuple1, string tuple2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Equal__SWIG_7(tuple1, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static int Equal(string cUnfTuple_t1, string cUnfTuple_t2, uint order, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Equal__SWIG_8(cUnfTuple_t1, cUnfTuple_t2, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static int Equal(string cUnfTuple_t1, string cUnfTuple_t2, uint order1, uint order2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Equal__SWIG_9(cUnfTuple_t1, cUnfTuple_t2, order1, order2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static int Equal(string cTuple_t1, uint order1, cSpaceDescriptor sd1, string cLNTuple_t2, uint order2, cSpaceDescriptor sd2) {
    int ret = TupleGeneratorPINVOKE.cTuple_Equal__SWIG_10(cTuple_t1, order1, cSpaceDescriptor.getCPtr(sd1), cLNTuple_t2, order2, cSpaceDescriptor.getCPtr(sd2));
    return ret;
  }

  public static int Compare(cTuple t1, cTuple t2, cDTDescriptor pDtd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Compare__SWIG_3(cTuple.getCPtr(t1), cTuple.getCPtr(t2), cDTDescriptor.getCPtr(pDtd));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int Compare(string dst, string src, cDTDescriptor pDtd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Compare__SWIG_4(dst, src, cDTDescriptor.getCPtr(pDtd));
    return ret;
  }

  public static int Compare(string tuple1, string tuple2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_Compare__SWIG_5(tuple1, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static int CompareLexicographically(string tuple1, string tuple2, cSpaceDescriptor pSd, uint dimension) {
    int ret = TupleGeneratorPINVOKE.cTuple_CompareLexicographically__SWIG_2(tuple1, tuple2, cSpaceDescriptor.getCPtr(pSd), dimension);
    return ret;
  }

  public static int CompareLexicographically(string tuple1, string tuple2, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_CompareLexicographically__SWIG_3(tuple1, tuple2, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static int ComparePartly(string cTuple_t1, string cNTuple_t2, cDTDescriptor pSd, uint startOrder) {
    int ret = TupleGeneratorPINVOKE.cTuple_ComparePartly(cTuple_t1, cNTuple_t2, cDTDescriptor.getCPtr(pSd), startOrder);
    return ret;
  }

  public static uint HashValue(string tuple, uint hashTableSize, cDTDescriptor dtd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_HashValue__SWIG_2(tuple, hashTableSize, cDTDescriptor.getCPtr(dtd));
    return ret;
  }

  public static void Print(string data, string delim, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_Print__SWIG_3(data, delim, cSpaceDescriptor.getCPtr(pSd));
  }

  public static void Print(string data, string delim, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_Print__SWIG_4(data, delim, cDTDescriptor.getCPtr(pSd));
  }

  public static void WriteAsText(string data, SWIGTYPE_p_cStream stream, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_WriteAsText(data, SWIGTYPE_p_cStream.getCPtr(stream), cSpaceDescriptor.getCPtr(pSd));
  }

  public static void Print2File(SWIGTYPE_p_FILE StreamInfo, string data, string delim, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_Print2File__SWIG_0(SWIGTYPE_p_FILE.getCPtr(StreamInfo), data, delim, cSpaceDescriptor.getCPtr(pSd));
  }

  public static void Print2File(SWIGTYPE_p_FILE StreamInfo, string data, string delim, cDTDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_Print2File__SWIG_1(SWIGTYPE_p_FILE.getCPtr(StreamInfo), data, delim, cDTDescriptor.getCPtr(pSd));
  }

  public static void PrintInfoCompare(uint basicCountCompare, uint treeHeight) {
    TupleGeneratorPINVOKE.cTuple_PrintInfoCompare(basicCountCompare, treeHeight);
  }

  public static void SaveToFileStatisticInfoCompare(SWIGTYPE_p_string fileName, SWIGTYPE_p_string typeRQ, int rq_min, int rq_max, bool new_typeRQ, double mTime, double timeOrderRQ, uint RQ_resultSize, int retry_RangeQuery, int count_RQ, double basicTime) {
    TupleGeneratorPINVOKE.cTuple_SaveToFileStatisticInfoCompare(SWIGTYPE_p_string.getCPtr(fileName), SWIGTYPE_p_string.getCPtr(typeRQ), rq_min, rq_max, new_typeRQ, mTime, timeOrderRQ, RQ_resultSize, retry_RangeQuery, count_RQ, basicTime);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static int GetTotalReadNodes() {
    int ret = TupleGeneratorPINVOKE.cTuple_GetTotalReadNodes();
    return ret;
  }

  public static void ResetStatistic() {
    TupleGeneratorPINVOKE.cTuple_ResetStatistic();
  }

  public static uint GetLSize(uint tupleLength, cDTDescriptor dtd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetLSize(tupleLength, cDTDescriptor.getCPtr(dtd));
    return ret;
  }

  public static uint GetSize(string data, cDTDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetSize__SWIG_2(data, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static uint GetMaxSize(string data, cDTDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetMaxSize__SWIG_1(data, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static uint GetUInt(string data, uint order, cSpaceDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetUInt__SWIG_1(data, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static int GetInt(string data, uint order, cSpaceDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_GetInt__SWIG_1(data, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static float GetFloat(string data, uint order, cSpaceDescriptor pSd) {
    float ret = TupleGeneratorPINVOKE.cTuple_GetFloat__SWIG_1(data, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static double GetDouble(string data, uint order, cSpaceDescriptor pSd) {
    double ret = TupleGeneratorPINVOKE.cTuple_GetDouble__SWIG_1(data, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static short GetShort(string data, uint order, cSpaceDescriptor pSd) {
    short ret = TupleGeneratorPINVOKE.cTuple_GetShort__SWIG_1(data, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static ushort GetUShort(string data, uint order, cSpaceDescriptor pSd) {
    ushort ret = TupleGeneratorPINVOKE.cTuple_GetUShort__SWIG_1(data, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static byte GetUByte(string data, uint order, cSpaceDescriptor pSd) {
    byte ret = TupleGeneratorPINVOKE.cTuple_GetUByte(data, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static char GetByte(string data, uint order, cSpaceDescriptor pSd) {
    char ret = TupleGeneratorPINVOKE.cTuple_GetByte__SWIG_1(data, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static byte GetUChar(string data, uint order, cDTDescriptor pSd) {
    byte ret = TupleGeneratorPINVOKE.cTuple_GetUChar__SWIG_1(data, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static string GetPChar(string data, uint order, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_GetPChar(data, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static string GetPValue(string data, uint order, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_GetPValue__SWIG_1(data, order, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static void SetValue(string data, uint order, int value, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_11(data, order, value, cSpaceDescriptor.getCPtr(pSd));
  }

  public static void SetValue(string data, uint order, uint value, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_12(data, order, value, cSpaceDescriptor.getCPtr(pSd));
  }

  public static void SetValue(string data, uint order, ushort value, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_13(data, order, value, cSpaceDescriptor.getCPtr(pSd));
  }

  public static void SetValue(string data, uint order, byte value, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_14(data, order, value, cSpaceDescriptor.getCPtr(pSd));
  }

  public static void SetValue(string data, uint order, float value, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_15(data, order, value, cSpaceDescriptor.getCPtr(pSd));
  }

  public static void SetValue(string data, uint order, char value, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_SetValue__SWIG_16(data, order, value, cSpaceDescriptor.getCPtr(pSd));
  }

  public static float UnitIntervalLength(string cTuple_t1, string cTuple_t2, uint order, cSpaceDescriptor pSd) {
    float ret = TupleGeneratorPINVOKE.cTuple_UnitIntervalLength__SWIG_1(cTuple_t1, cTuple_t2, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static double TaxiCabDistance(string cTuple_t1, string cTuple_t2, cDTDescriptor pSd) {
    double ret = TupleGeneratorPINVOKE.cTuple_TaxiCabDistance(cTuple_t1, cTuple_t2, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static string Subtract(string cTuple_t1, string cTuple_t2, string cTuple_result, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_Subtract__SWIG_0(cTuple_t1, cTuple_t2, cTuple_result, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static string Add(string cTuple_t1, string cTuple_t2, string cTuple_result, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_Add__SWIG_0(cTuple_t1, cTuple_t2, cTuple_result, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static void Subtract(string cTuple_t1, string cTuple_t2, string cTuple_result, uint order, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_Subtract__SWIG_1(cTuple_t1, cTuple_t2, cTuple_result, order, cSpaceDescriptor.getCPtr(pSd));
  }

  public static void Add(string cTuple_t1, string cTuple_t2, string cTuple_result, uint order, cSpaceDescriptor pSd) {
    TupleGeneratorPINVOKE.cTuple_Add__SWIG_1(cTuple_t1, cTuple_t2, cTuple_result, order, cSpaceDescriptor.getCPtr(pSd));
  }

  public static double TaxiCabDistanceValue(string cTuple_t1, string cTuple_t2, uint order, cSpaceDescriptor pSd) {
    double ret = TupleGeneratorPINVOKE.cTuple_TaxiCabDistanceValue(cTuple_t1, cTuple_t2, order, cSpaceDescriptor.getCPtr(pSd));
    return ret;
  }

  public static uint GetDimension(cDTDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetDimension(cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public void AddToHistogram(SWIGTYPE_p_p_cHistogram histogram, cDTDescriptor dtd) {
    TupleGeneratorPINVOKE.cTuple_AddToHistogram__SWIG_0(swigCPtr, SWIGTYPE_p_p_cHistogram.getCPtr(histogram), cDTDescriptor.getCPtr(dtd));
  }

  public static void AddToHistogram(string cTuple_tuple, SWIGTYPE_p_p_cHistogram histogram, cDTDescriptor dtd) {
    TupleGeneratorPINVOKE.cTuple_AddToHistogram__SWIG_1(cTuple_tuple, SWIGTYPE_p_p_cHistogram.getCPtr(histogram), cDTDescriptor.getCPtr(dtd));
  }

  public static uint Encode(uint method, string sourceBuffer, string encodedBuffer, cDTDescriptor sd, uint tupleLength) {
    uint ret = TupleGeneratorPINVOKE.cTuple_Encode__SWIG_0(method, sourceBuffer, encodedBuffer, cDTDescriptor.getCPtr(sd), tupleLength);
    return ret;
  }

  public static uint Encode(uint method, string sourceBuffer, string encodedBuffer, cDTDescriptor sd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_Encode__SWIG_1(method, sourceBuffer, encodedBuffer, cDTDescriptor.getCPtr(sd));
    return ret;
  }

  public static uint Decode(uint method, string encodedBuffer, string decodedBuffer, cDTDescriptor sd, uint tupleLength) {
    uint ret = TupleGeneratorPINVOKE.cTuple_Decode__SWIG_0(method, encodedBuffer, decodedBuffer, cDTDescriptor.getCPtr(sd), tupleLength);
    return ret;
  }

  public static uint Decode(uint method, string encodedBuffer, string decodedBuffer, cDTDescriptor sd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_Decode__SWIG_1(method, encodedBuffer, decodedBuffer, cDTDescriptor.getCPtr(sd));
    return ret;
  }

  public static uint GetEncodedSize(uint method, string sourceBuffer, cDTDescriptor sd, uint tupleLength) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetEncodedSize__SWIG_0(method, sourceBuffer, cDTDescriptor.getCPtr(sd), tupleLength);
    return ret;
  }

  public static uint GetEncodedSize(uint method, string sourceBuffer, cDTDescriptor sd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_GetEncodedSize__SWIG_1(method, sourceBuffer, cDTDescriptor.getCPtr(sd));
    return ret;
  }

  public static uint EncodedSize(uint method, string sourceBuffer, cDTDescriptor sd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_EncodedSize(method, sourceBuffer, cDTDescriptor.getCPtr(sd));
    return ret;
  }

  public int GetLength() {
    int ret = TupleGeneratorPINVOKE.cTuple_GetLength__SWIG_0(swigCPtr);
    return ret;
  }

  public static int GetLength(string cTuple_t1, cDTDescriptor pSd) {
    int ret = TupleGeneratorPINVOKE.cTuple_GetLength__SWIG_1(cTuple_t1, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static uint CutTuple(string cBitString_Mask, string cTuple_RI, string cTuple_Key, string cTuple_Result, cDTDescriptor pSd) {
    uint ret = TupleGeneratorPINVOKE.cTuple_CutTuple(cBitString_Mask, cTuple_RI, cTuple_Key, cTuple_Result, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static string MergeTuple(string cBitString_Mask, string cTuple_RI, string cTuple_Key, string cTuple_Result, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_MergeTuple(cBitString_Mask, cTuple_RI, cTuple_Key, cTuple_Result, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static string SetMask(string cBitString_Mask, string cTuple_RI, string cTuple_Key, string cBitString_Result, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_SetMask__SWIG_0(cBitString_Mask, cTuple_RI, cTuple_Key, cBitString_Result, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static string SetMask(string cTuple_t1, string cTuple_t2, string cBitString_Result, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_SetMask__SWIG_1(cTuple_t1, cTuple_t2, cBitString_Result, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static string SetMask(string cTuple_t1, string cBitString_Mask1, string cTuple_t2, string cBitString_Mask2, string cBitString_Result, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_SetMask__SWIG_2(cTuple_t1, cBitString_Mask1, cTuple_t2, cBitString_Mask2, cBitString_Result, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static string SetMinRefItem(string cTuple_RI, string cTuple_Key, string cTuple_Result, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_SetMinRefItem(cTuple_RI, cTuple_Key, cTuple_Result, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static string MergeMasks(string cBitString_Mask1, string cBitString_Mask2, string cTuple_RI1, string cTuple_RI2, string cBitString_Result, cDTDescriptor pSd) {
    string ret = TupleGeneratorPINVOKE.cTuple_MergeMasks(cBitString_Mask1, cBitString_Mask2, cTuple_RI1, cTuple_RI2, cBitString_Result, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static bool IsCompatible(string cBitString_Mask, string cTuple_RI, string cTuple_Key, cDTDescriptor pSd) {
    bool ret = TupleGeneratorPINVOKE.cTuple_IsCompatible(cBitString_Mask, cTuple_RI, cTuple_Key, cDTDescriptor.getCPtr(pSd));
    return ret;
  }

  public static readonly uint LengthType = TupleGeneratorPINVOKE.cTuple_LengthType_get();
  public static new readonly char CODE = TupleGeneratorPINVOKE.cTuple_CODE_get();
}

}
