//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TupleGeneratorWrapper {

public enum Distribution {
  Uniform = 1,
  Normal = 2,
  Logonormal = 3,
  Diagonal = 4,
  Sierpinski = 5,
  Bit = 6
}

}
