//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TupleGeneratorWrapper {

public enum QueryType {
  PointQuery = 1,
  NarrowRangeQuery = 2,
  PartialMatchQuery = 3,
  RangeQuery = 4,
  CartesianRangeQuery = 5
}

}
