//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TupleGeneratorWrapper {

public class TupleGenerator {
  public static string FormatDouble(double value) {
    string ret = TupleGeneratorPINVOKE.FormatDouble(value);
    return ret;
  }

  public static string FormatFloat(float value) {
    string ret = TupleGeneratorPINVOKE.FormatFloat(value);
    return ret;
  }

  public static string GetTableName(string path) {
    string ret = TupleGeneratorPINVOKE.GetTableName(path);
    return ret;
  }

}

}
