//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TupleGeneratorWrapper {

public class vector_uint : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<uint>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vector_uint(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vector_uint obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(vector_uint obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~vector_uint() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TupleGeneratorPINVOKE.delete_vector_uint(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public vector_uint(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (uint element in c) {
      this.Add(element);
    }
  }

  public vector_uint(global::System.Collections.Generic.IEnumerable<uint> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (uint element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public uint this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(uint[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(uint[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, uint[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public uint[] ToArray() {
    uint[] array = new uint[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<uint> global::System.Collections.Generic.IEnumerable<uint>.GetEnumerator() {
    return new vector_uintEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new vector_uintEnumerator(this);
  }

  public vector_uintEnumerator GetEnumerator() {
    return new vector_uintEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class vector_uintEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<uint>
  {
    private vector_uint collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public vector_uintEnumerator(vector_uint collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public uint Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (uint)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public vector_uint() : this(TupleGeneratorPINVOKE.new_vector_uint__SWIG_0(), true) {
  }

  public vector_uint(vector_uint other) : this(TupleGeneratorPINVOKE.new_vector_uint__SWIG_1(vector_uint.getCPtr(other)), true) {
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    TupleGeneratorPINVOKE.vector_uint_Clear(swigCPtr);
  }

  public void Add(uint x) {
    TupleGeneratorPINVOKE.vector_uint_Add(swigCPtr, x);
  }

  private uint size() {
    uint ret = TupleGeneratorPINVOKE.vector_uint_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = TupleGeneratorPINVOKE.vector_uint_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = TupleGeneratorPINVOKE.vector_uint_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    TupleGeneratorPINVOKE.vector_uint_reserve(swigCPtr, n);
  }

  public vector_uint(int capacity) : this(TupleGeneratorPINVOKE.new_vector_uint__SWIG_2(capacity), true) {
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint getitemcopy(int index) {
    uint ret = TupleGeneratorPINVOKE.vector_uint_getitemcopy(swigCPtr, index);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint getitem(int index) {
    uint ret = TupleGeneratorPINVOKE.vector_uint_getitem(swigCPtr, index);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, uint val) {
    TupleGeneratorPINVOKE.vector_uint_setitem(swigCPtr, index, val);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(vector_uint values) {
    TupleGeneratorPINVOKE.vector_uint_AddRange(swigCPtr, vector_uint.getCPtr(values));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public vector_uint GetRange(int index, int count) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.vector_uint_GetRange(swigCPtr, index, count);
    vector_uint ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_uint(cPtr, true);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, uint x) {
    TupleGeneratorPINVOKE.vector_uint_Insert(swigCPtr, index, x);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, vector_uint values) {
    TupleGeneratorPINVOKE.vector_uint_InsertRange(swigCPtr, index, vector_uint.getCPtr(values));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    TupleGeneratorPINVOKE.vector_uint_RemoveAt(swigCPtr, index);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    TupleGeneratorPINVOKE.vector_uint_RemoveRange(swigCPtr, index, count);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static vector_uint Repeat(uint value, int count) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.vector_uint_Repeat(value, count);
    vector_uint ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_uint(cPtr, true);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    TupleGeneratorPINVOKE.vector_uint_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    TupleGeneratorPINVOKE.vector_uint_Reverse__SWIG_1(swigCPtr, index, count);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, vector_uint values) {
    TupleGeneratorPINVOKE.vector_uint_SetRange(swigCPtr, index, vector_uint.getCPtr(values));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(uint value) {
    bool ret = TupleGeneratorPINVOKE.vector_uint_Contains(swigCPtr, value);
    return ret;
  }

  public int IndexOf(uint value) {
    int ret = TupleGeneratorPINVOKE.vector_uint_IndexOf(swigCPtr, value);
    return ret;
  }

  public int LastIndexOf(uint value) {
    int ret = TupleGeneratorPINVOKE.vector_uint_LastIndexOf(swigCPtr, value);
    return ret;
  }

  public bool Remove(uint value) {
    bool ret = TupleGeneratorPINVOKE.vector_uint_Remove(swigCPtr, value);
    return ret;
  }

}

}
