//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TupleGeneratorWrapper {

public class vector_cTuple_ptr : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<cTuple>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vector_cTuple_ptr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vector_cTuple_ptr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(vector_cTuple_ptr obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~vector_cTuple_ptr() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TupleGeneratorPINVOKE.delete_vector_cTuple_ptr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public vector_cTuple_ptr(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (cTuple element in c) {
      this.Add(element);
    }
  }

  public vector_cTuple_ptr(global::System.Collections.Generic.IEnumerable<cTuple> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (cTuple element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public cTuple this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(cTuple[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(cTuple[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, cTuple[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public cTuple[] ToArray() {
    cTuple[] array = new cTuple[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<cTuple> global::System.Collections.Generic.IEnumerable<cTuple>.GetEnumerator() {
    return new vector_cTuple_ptrEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new vector_cTuple_ptrEnumerator(this);
  }

  public vector_cTuple_ptrEnumerator GetEnumerator() {
    return new vector_cTuple_ptrEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class vector_cTuple_ptrEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<cTuple>
  {
    private vector_cTuple_ptr collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public vector_cTuple_ptrEnumerator(vector_cTuple_ptr collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public cTuple Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (cTuple)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public vector_cTuple_ptr() : this(TupleGeneratorPINVOKE.new_vector_cTuple_ptr__SWIG_0(), true) {
  }

  public vector_cTuple_ptr(vector_cTuple_ptr other) : this(TupleGeneratorPINVOKE.new_vector_cTuple_ptr__SWIG_1(vector_cTuple_ptr.getCPtr(other)), true) {
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_Clear(swigCPtr);
  }

  public void Add(cTuple x) {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_Add(swigCPtr, cTuple.getCPtr(x));
  }

  private uint size() {
    uint ret = TupleGeneratorPINVOKE.vector_cTuple_ptr_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = TupleGeneratorPINVOKE.vector_cTuple_ptr_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = TupleGeneratorPINVOKE.vector_cTuple_ptr_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_reserve(swigCPtr, n);
  }

  public vector_cTuple_ptr(int capacity) : this(TupleGeneratorPINVOKE.new_vector_cTuple_ptr__SWIG_2(capacity), true) {
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  private cTuple getitemcopy(int index) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.vector_cTuple_ptr_getitemcopy(swigCPtr, index);
    cTuple ret = (cPtr == global::System.IntPtr.Zero) ? null : new cTuple(cPtr, false);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private cTuple getitem(int index) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.vector_cTuple_ptr_getitem(swigCPtr, index);
    cTuple ret = (cPtr == global::System.IntPtr.Zero) ? null : new cTuple(cPtr, false);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, cTuple val) {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_setitem(swigCPtr, index, cTuple.getCPtr(val));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(vector_cTuple_ptr values) {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_AddRange(swigCPtr, vector_cTuple_ptr.getCPtr(values));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public vector_cTuple_ptr GetRange(int index, int count) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.vector_cTuple_ptr_GetRange(swigCPtr, index, count);
    vector_cTuple_ptr ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_cTuple_ptr(cPtr, true);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, cTuple x) {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_Insert(swigCPtr, index, cTuple.getCPtr(x));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, vector_cTuple_ptr values) {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_InsertRange(swigCPtr, index, vector_cTuple_ptr.getCPtr(values));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_RemoveAt(swigCPtr, index);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_RemoveRange(swigCPtr, index, count);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static vector_cTuple_ptr Repeat(cTuple value, int count) {
    global::System.IntPtr cPtr = TupleGeneratorPINVOKE.vector_cTuple_ptr_Repeat(cTuple.getCPtr(value), count);
    vector_cTuple_ptr ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_cTuple_ptr(cPtr, true);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_Reverse__SWIG_1(swigCPtr, index, count);
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, vector_cTuple_ptr values) {
    TupleGeneratorPINVOKE.vector_cTuple_ptr_SetRange(swigCPtr, index, vector_cTuple_ptr.getCPtr(values));
    if (TupleGeneratorPINVOKE.SWIGPendingException.Pending) throw TupleGeneratorPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(cTuple value) {
    bool ret = TupleGeneratorPINVOKE.vector_cTuple_ptr_Contains(swigCPtr, cTuple.getCPtr(value));
    return ret;
  }

  public int IndexOf(cTuple value) {
    int ret = TupleGeneratorPINVOKE.vector_cTuple_ptr_IndexOf(swigCPtr, cTuple.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(cTuple value) {
    int ret = TupleGeneratorPINVOKE.vector_cTuple_ptr_LastIndexOf(swigCPtr, cTuple.getCPtr(value));
    return ret;
  }

  public bool Remove(cTuple value) {
    bool ret = TupleGeneratorPINVOKE.vector_cTuple_ptr_Remove(swigCPtr, cTuple.getCPtr(value));
    return ret;
  }

}

}
